// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal.WRC.Total.com.Data;

namespace Portal.WRC.Total.com.Migrations.NoticiasContextoMigrations
{
    [DbContext(typeof(NoticiasContexto))]
    partial class NoticiasContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Portal.WRC.Total.com.Models.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ntc_curta_descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ntc_data_atualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ntc_data_insercao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ntc_pais_rally")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntc_texto_noticia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ntc_titulo_noticia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Noticia");
                });
#pragma warning restore 612, 618
        }
    }
}
