// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal.WRC.Total.com.Data;

namespace Portal.WRC.Total.com.Migrations.PilotosContextoMigrations
{
    [DbContext(typeof(PilotosContexto))]
    [Migration("20210905013900_ScriptPilotosContexto")]
    partial class ScriptPilotosContexto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Portal.WRC.Total.com.Models.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("plt_data_atualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("plt_data_insercao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("plt_data_nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("plt_nome_completo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plt_nome_curto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plt_pais_nascimento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Piloto");
                });
#pragma warning restore 612, 618
        }
    }
}
