// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal.WRC.Total.com.Data;

namespace Portal.WRC.Total.com.Migrations
{
    [DbContext(typeof(EquipesContexto))]
    partial class EquipesContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Portal.WRC.Total.com.Models.Equipes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("eqp_data_atualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("eqp_data_insercao")
                        .HasColumnType("datetime2");

                    b.Property<string>("eqp_nome_chefe_equipe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eqp_nome_completo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eqp_nome_curto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eqp_pais_origem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eqp_url_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eqp_url_site")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipes");
                });
#pragma warning restore 612, 618
        }
    }
}
